### PR TITLE
Decode memory-efficiently copied files from base64

### LINKED ISSUE #9: `System.OutOfMemoryException` when copying large file
Repro:

```
$ go get github.com/packer-community/winrmcp
$ cd /path/to/winrmcp
$ make
$ bin/winrmcp -user vagrant -pass vagrant -addr localhost:2894 /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso VBoxGuestAdditions.iso
#< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">Exception calling "FromBase64String" with "1" argument(s): "Create excepti_x000D__x000A_</S><S S="Error">on of type System.OutOfMemoryException."_x000D__x000A_</S><S S="Error">At line:15 char:47_x000D__x000A_</S><S S="Error">+             $bytes = [System.Convert]::FromBase64String &lt;&lt;&lt;&lt; ($base64_string)_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S><S S="Error">    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : DotNetMethodException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S><S S="Error">Exception calling "WriteAllBytes" with "2" argument(s): "Value cannot be NUL_x000D__x000A_</S><S S="Error">L._x000D__x000A_</S><S S="Error">Paremeter name: bytes"_x000D__x000A_</S><S S="Error">At line:16 char:35_x000D__x000A_</S><S S="Error">+             [System.IO.File]::WriteAllBytes &lt;&lt;&lt;&lt; ($dest_file_path, $bytes)_x000D__x000A_</S><S S="Error">    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : DotNetMethodException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>Error restoring file from $env:TEMP\winrmcp-563f367b-b70a-7f21-15a2-cf378c7ce057.tmp to VBoxGuestAdditions.iso: restore operation returned code=1
```

When I raise the Memory limit of PowerShell, the problem goes away (i.e., I can successfully copy the same big file to the VM) - inspiration from [here](http://jeffwouters.nl/index.php/2014/03/out-of-memory-exception-in-powershell/):

``` bat
powershell -Command "Set-Item WSMan:\localhost\Shell\MaxMemoryPerShellMB 1024" <NUL
%SystemRoot%\SysWOW64\cmd.exe /c powershell -Command "Set-Item WSMan:\localhost\Shell\MaxMemoryPerShellMB 1024" <NUL
```

Size of the uploaded file: 56M (from `ls -lh`)

Found when using [boxcutter/windows](https://github.com/boxcutter/windows) to build a base box.

I think this is caused by [cp.go:128](https://github.com/packer-community/winrmcp/blob/master/winrmcp/cp.go#L128) which in this case tries to decode a ~78MB base64 string (if encoded in ASCII) into ~56MB in-memory bytes (and might still be holding another ~78MB string array in memory). I think it would be better if the decoding of the base64 file was done in a "streaming way" - read n lines, decode them from base64, append the bytes to a temp binary file, repeat, and at the end (when end of base64 file reached), move the temp binary file to the destination.

OS X: 10.11.1 (host)
Win: 7 Pro x64 Czech (guest) - without SP1
VirtualBox: 5.0.8

Notes: the error message was translated from Czech, because Czech version of Windows (which I am using) does log certain parts of error output in the Windows language (and some parts in English). Specifically:
- "Create exception of type System.OutOfMemoryException."
- "Value cannot be NUL"
- "Parameter names"

So just saying in case you would like to Google them (but I think the problem is obvious even without Googling them).

### PR DESCRIPTION
**Pull request by dusek**
Current code decodes the base64-encoded representation of the copied file
by 3 steps during which it holds the whole file in memory:
- reading the file into array of base64 strings for each line
- creating a single base64 string for whole file
- decoding the string into bytes array containing whole file in binary
  representation

So let's change it into being more efficient - by performing this
decoding pipeline line-by-line: read one line of base64 file, decode it
into bytes, and write (append) it to the destination binary file, and
repeat until whole file is converted.

I tested correctness by computing md5 of the binary result and comparing
with md5 sum computed on the machine on which winrmcp was run, in these
scenarios:
- 187MB binary file (btw. copied successfully with MaxMemoryPerShellMB=150MB)
- empty file (i.e. with length 0 bytes)
- 2kB text file (main.go :-)
- 50kB text file (main.go contatenated many times)

Performance-wise: on a Win7 Pro x64 machine without the VirtualBox
additions installed, copying a 187MB file took 11 minutes for copying
over the temporary base64 representation, and approx.  12-13 seconds for
decoding the base64 representation into original binary form. I have not
compared it the current method, nor tried on a machine with VirtualBox
additions installed.

This prevents `OutOfMemoryException` in some cases (most notably when
packer copies VBoxGuestAdditions.iso during some installations of
Windows).

Fixes #9

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks @dusek, this is great. I'll take a look through and provide some feedback.

**Comment by EikeVerdenhalven** [comment]
The loop can be written a little more compact. See #19 (which was my attempt, before I saw it's a dupe).

**Comment by dylanmei** [comment]
@dusek Would you kindly resolve any conflicts? If it's been too long we'll work with @EikeVerdenhalven -- the changes you have both made are similar.

**Comment by dusek** [comment]
@dylanmei rebased (the only conflict seems to have been due to removing trailing whitespace in fd76b28 at [`winrmcp/cp.go:130`](https://github.com/packer-community/winrmcp/commit/fd76b2836f96cee89c5aa525b748aa4538cea2b4#diff-460a60b3365f82086e0b1eeb37420902L128)

**Comment by dylanmei** [comment]
Fantastic, thanks!

**Pull request merged**
